modLoader = "javafml"
loaderVersion = "[45,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "walkers"
version = "${version}"
displayName = "Walkers"
authors = "To_Craft"
description = '''
Become a Woodwalker/animagus!
'''
#logoFile = ""

[[dependencies.walkers]]
modId = "forge"
mandatory = true
versionRange = "[45,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.walkers]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.4,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.walkers]]
modId = "craftedcore"
mandatory = true
versionRange = "*"
ordering = "AFTER"
side = "BOTH"