modLoader = "javafml"
loaderVersion = "[1,)"
#issueTrackerURL = ""
license = "MIT"

[[mixins]]
config = "walkers-neoforge.mixins.json"
[[mixins]]
config = "walkers.mixins.json"

[[mods]]
modId = "walkers"
version = "${version}"
displayName = "Walkers"
authors = "To_Craft"
description = '''
Become a Woodwalker/animagus!
'''
#logoFile = ""

[[dependencies.walkers]]
modId = "minecraft"
mandatory = true
versionRange = "[${minecraft_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.walkers]]
modId = "craftedcore"
mandatory = true
versionRange = "[${craftedcore_version},)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.walkers]]
modId = "architectury"
mandatory = true
versionRange = "[${architectury_version},)"
ordering = "AFTER"
side = "BOTH"